// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $custom_elements from "./routes/custom-elements.tsx";
import * as $form_processor from "./routes/form-processor.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $lit from "./routes/lit.tsx";
import * as $third_party from "./routes/third-party.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $WCWrappedCounter from "./islands/WCWrappedCounter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/custom-elements.tsx": $custom_elements,
    "./routes/form-processor.tsx": $form_processor,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/lit.tsx": $lit,
    "./routes/third-party.tsx": $third_party,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/WCWrappedCounter.tsx": $WCWrappedCounter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
